services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wordpress_db:/var/www/html/wordpress
    depends_on:    
      - wordpress
    ports:
      - "443:443"
    networks:
       - inception
    container_name: nginx
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    networks:
       - inception
    volumes:
      - mariadb_db:/var/lib/mysql
    container_name: mariadb
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_db:/var/www/html/wordpress
    depends_on:
      - mariadb
    container_name: wordpress

volumes:
    wordpress_db:
      name: wordpress_db
      driver: local 
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/${USER}/data/wordpress'
    mariadb_db:
      name: mariadb_db
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/${USER}/data/mariadb'

networks:
   inception:
     driver: bridge
