services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    volumes:
      - ./requirements/nginx/public:/var/www
      - ./requirements/nginx/conf:/etc/nginx/http.d/
      - ./requirements/tools:/etc/nginx/ssl/
    restart: always
    ports:
      - "443:443"
    container_name: nginx