
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "443:443"
    networks:
       - inception
    container_name: nginx
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    # env_file: .env
    networks:
       - inception
    volumes:
      - mariadb_db:/var/lib/mysql
    expose:
      - "3306"
    container_name: mariadb
    secrets:
      - root_passwords
      - database_passwords
  wordpress:
    build:
      context: ./requirements/WordPress
      dockerfile: Dockerfile
    restart: on-failure
    #env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_db:/var/www/wordpress
    depends_on:    # WordPress démarrera uniquement après MariaDB (sinon il ne pourra pas configurer la base de données...)
      - mariadb
    expose:
      - "9000"
    container_name: wordpress
    secrets:
      - wp_passwords
      - database_passwords
      - root_passwords

volumes:
    wordpress_db:
      name: mariadb
      driver: local # ici nous stockons le volume en local
      driver_opts:
        type: 'none'     # aucun type spécifique
        o: 'bind'
        device: '/home/${USER}/data/wordpress' #Ou stocker le dossier sur votre ordinateur en local
    mariadb_db:
      name: mariadb
      driver: local
      driver_opts:
        type: 'none' 
        o: 'bind'    
        device: '/home/${USER}/data/mariadb'
networks:
   inception:
     driver: bridge

secrets:
     database_passwords:
      file: ../secrets/db_password.txt
     root_passwords:
      file: ../secrets/db_root_password.txt
     wp_passwords:
      file: ../secrets/credentials.txt